<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAuVri2N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAuVri2N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAuVri2N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAuVri2N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAuVri2N\App_KernelDevDebugContainer([
    'container.build_hash' => 'AuVri2N',
    'container.build_id' => 'f22367da',
    'container.build_time' => 1600379934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAuVri2N');
